export const INITIALIZE_APP_REQUEST = 'VARICON/@src/app/INITIALIZE_APP_REQUEST';
export const INITIALIZE_APP_SUCCESS = 'VARICON/@src/app/INITIALIZE_APP_SUCCESS';
export const INITIALIZE_APP_FAILURE = 'VARICON/@src/app/INITIALIZE_APP_FAILURE';

export const LOAD_INITIAL_REQUEST = 'VARICON/@src/app/LOAD_INITIAL_REQUEST';
export const LOAD_INITIAL_SUCCESS = 'VARICON/@src/app/LOAD_INITIAL_SUCCESS';
export const LOAD_INITIAL_FAILURE = 'VARICON/@src/app/LOAD_INITIAL_FAILURE';

export const API_URL = `${process.env.REACT_APP_API_URL}/api/v1`;

export const API_DJANGO = {
  baseURL: '/api/v1',
  headers: {
    'Content-Type': 'application/json',
    // 'X-CSRFToken': getCookie('csrftoken'),
  },
};

export const API = {
  name: 'api',
  baseURL: API_URL,
  headers: {
    'Content-Type': 'application/json',
  },
};

export const LOGIN_API = '/user/login/';
export const USER_FROM_TOKEN_API = '/user/user_data/';
export const DEFAULT_TAX_API = '/tax-setting/default_tax/';
export const PURCHASE_ORDERS_API = '/purchase-order/';
export const PURCHASE_ORDERS_SUPPLIERS_API = '/purchase-order/suppliers/';
export const PURCHASE_ORDERS_PROJECTS_API = '/purchase-order/projects/';
export const PURCHASE_ORDERS_AUTOGENERATED_PO_NUMBER_API =
  '/purchase-order/autogenerated_po/';
export const PURCHASE_ORDERS_TAX_LIST_API = '/purchase-order/tax_list/';
export const PURCHASE_ORDERS_RESOURCE_CODES_API =
  '/purchase-order/resource_codes/';
export const PURCHASE_ORDERS_PROJECT_ADDRESS_API =
  '/purchase-order/project_address/';
export const PURCHASE_ORDERS_WORKFLOW_LIST_API = '/purchase-order-workflow/';
export const PURCHASE_ORDERS_WORKFLOW_DETAIL_API =
  '/purchase-order-workflow/:id/';
export const PURCHASE_ORDERS_COUNTRIES_API = '/purchase-order/countries/';
export const PURCHASE_ORDERS_STATES_API = '/purchase-order/states/';
export const PURCHASE_ORDERS_POSSIBLE_APPROVERS_API =
  '/purchase-order/possible_approvers/';
export const PURCHASE_ORDERS_USERS_TO_NOMINATE_API =
  '/purchase-order/search_users_for_nominate/';
export const PURCHASE_ORDERS_RESOURCE_CODE_DETAIL_API =
  '/purchase-order/resource_code_data/';
export const PURCHASE_ORDERS_DETAIL_API = '/purchase-order/:id/';
export const PURCHASE_ORDERS_DETAIL_WORKFLOW_STEPS_API =
  '/purchase-order/:id/workflow_steps/';
export const PURCHASE_ORDERS_DETAIL_ADD_APPROVER_API =
  '/purchase-order/:id/add_approver/';
export const PURCHASE_ORDERS_DETAIL_DELETE_APPROVER_API =
  '/purchase-order/:id/delete_approver/';
export const PURCHASE_ORDERS_COMMENT_API = '/purchase-order-comment/';
export const PURCHASE_ORDERS_COMMENT_ID_API = '/purchase-order-comment/:id/';
export const PURCHASE_ORDERS_CANCEL_PO_API = '/purchase-order/:id/cancel_po/';
export const PURCHASE_ORDERS_NEXT_STEP_API =
  '/purchase-order/:id/move_step_po/';
export const PURCHASE_ORDERS_REJECT_API = '/purchase-order/:id/reject_po/';
export const PURCHASE_ORDERS_REVOKE_API = '/purchase-order/:id/revoke_po/';
export const PURCHASE_ORDERS_DOWNLOAD_PDF_API =
  '/purchase-order/:id/purchase_order_pdf/';
export const PURCHASE_ORDERS_MAIN_WORKFLOW_STEPS_API =
  '/purchase-order/main_workflow_steps/';
export const PURCHASE_ORDERS_UPDATE_DELIVERY_STATUS =
  '/purchase-order/:id/update_delivery_status/';
export const PURCHASE_ORDERS_SUBTASKS_API = '/purchase-order/sub_tasks/';
export const PURCHASE_ORDERS_COST_CENTER = '/purchase-order/cost_centers/';
export const PURCHASE_ORDERS_IVREF_API = '/purchase-order-invoice-ref-no/';
export const PURCHASE_ORDERS_IVREF_ID_API =
  '/purchase-order-invoice-ref-no/:id/';
export const PURCHASE_ORDERS_CHANGE_DOCKET_STATUS_API =
  '/purchase-order/change_docket_status/';
export const PURCHASE_ORDERS_WORKFLOW_ROLES = `/purchase-order-workflow/roles/`;

export const COST_CENTER = '/costcenter/';

export const RESOURCE_TAG_API = '/v1.1/resource-tag/';

// settings equipments
export const SETTINGS_EQUIPMENTS_API = '/v1.1/equipment/';

// employees
export const EMPLOYEES_API = '/employee/list_employee/';
export const EMPLOYEE_API = '/employee/';
export const EMPLOYEE_RESOURCE_CODES_API =
  '/employee/get_default_resource_codes/';
export const EMPLOYEE_DETAIL_API = '/employee/:id/';
export const SEND_PIN_RESET_LINK_API = '/employee/send_pin_reset_link/';
// timesheet
export const TIMESHEET_EXPORT_API = 'timesheet/export_timesheet/';
export const TIMESHEET_TEMPLATE_DOWNLOAD_API =
  'timesheet/export_timesheet_template/';
// supplier
export const SUPPLIER_TEMPLATE_DOWNLOAD_API =
  'mobile/supplier/supplier_sample_template/';

// v1.1

export const GET_DCT_DATA = '/dct/list_aggregate_dcts/';
export const DELETE_DCT_DATA = '/dct/delete_multiple_dcts/';
export const TIMESHEET_DATA = '/dct/list_sub_dcts/';
export const DOCKET_DCTS = '/dct/list_docket_dcts/';
export const TIMESHEET_DCTS = '/dct/list_timesheet_dcts/';
export const TASKS_DATA = '/dct/get_tasks/';
export const RESOURCE_DATA = '/dct/get_resources/';
export const COST_CENTER_DATA = '/dct/get_cost_centers/';
export const ADD_DCT = '/dct/create_manual_dct/';
export const UPDATE_DCT = '/dct/1759/update_manual_dct/';
export const APPROVE_DCTS = '/dct/approve_unapprove_multiple_dcts/';
export const ADD_ATTACHMENT = '/attachment/';
export const ADD_NOTES = '/dct/save_attachments_notes/';
export const GET_NOTES = '/dct/get_attachments_notes/';
